'use strict';

/**
 * Group normalised HAR records by (method, templated-path) and emit an
 * OpenAPI 3.0 document. Per-status response schemas are merged across all
 * samples for that group so the emitted contract describes what the
 * consumer ACTUALLY read across the captured run — not just one example.
 */

const { templatePath } = require('./pathTemplate');
const { inferSchema, mergeSchemas } = require('./schemaInfer');

/**
 * @param records normalised HAR records (output of normaliseEntries())
 * @param opts    { title, version, baseUrl, dynamicPatterns }
 * @returns       OpenAPI 3.0 document (plain JS object)
 */
function harToOpenapi(records, opts = {}) {
  const groups = new Map();   // key: "METHOD /templated/path"

  for (const r of records) {
    const { templated, paramNames } = templatePath(r.path, {
      dynamicPatterns: opts.dynamicPatterns,
    });
    const key = `${r.method} ${templated}`;
    let g = groups.get(key);
    if (!g) {
      g = {
        method: r.method.toLowerCase(),
        path: templated,
        paramNames,
        requestSchema: undefined,
        responses: new Map(),    // status → merged schema (or null = saw status, no JSON body)
      };
      groups.set(key, g);
    }

    if (r.requestBody !== undefined) {
      const sample = inferSchema(r.requestBody);
      g.requestSchema = g.requestSchema ? mergeSchemas(g.requestSchema, sample) : sample;
    }

    if (r.responseStatus) {
      const status = String(r.responseStatus);
      const schema = r.responseBody !== undefined ? inferSchema(r.responseBody) : null;
      if (schema) {
        const existing = g.responses.get(status);
        g.responses.set(status, existing ? mergeSchemas(existing, schema) : schema);
      } else if (!g.responses.has(status)) {
        g.responses.set(status, null);
      }
    }
  }

  // Build the OpenAPI doc.
  const paths = {};
  for (const g of groups.values()) {
    const pItem = paths[g.path] || (paths[g.path] = {});
    const op = {};

    if (g.paramNames.length > 0) {
      op.parameters = g.paramNames.map(name => ({
        name, in: 'path', required: true, schema: { type: 'string' },
      }));
    }

    if (g.requestSchema) {
      op.requestBody = {
        required: true,
        content: { 'application/json': { schema: g.requestSchema } },
      };
    }

    const responses = {};
    if (g.responses.size === 0) {
      responses['200'] = { description: 'OK' };
    } else {
      // Sort numerically for stable output.
      const statuses = [...g.responses.keys()].sort((a, b) => Number(a) - Number(b));
      for (const status of statuses) {
        const schema = g.responses.get(status);
        const r = { description: defaultDescriptionFor(status) };
        if (schema) r.content = { 'application/json': { schema } };
        responses[status] = r;
      }
    }
    op.responses = responses;

    pItem[g.method] = op;
  }

  const doc = {
    openapi: '3.0.0',
    info: {
      title: opts.title || 'Captured consumer contract',
      version: opts.version || '0.1.0',
      description:
        'Generated by `specshield bdct capture` from recorded HAR traffic. ' +
        'Reflects only the endpoints/fields the consumer actually called/read.',
    },
    paths: sortObject(paths),   // stable, alphabetical output
  };
  if (opts.baseUrl) doc.servers = [{ url: String(opts.baseUrl) }];
  // Re-order top-level so `servers` appears between `info` and `paths` (idiomatic).
  if (opts.baseUrl) {
    return { openapi: doc.openapi, info: doc.info, servers: doc.servers, paths: doc.paths };
  }
  return doc;
}

function defaultDescriptionFor(status) {
  const n = Number(status);
  if (n >= 200 && n < 300) return 'Successful response';
  if (n >= 300 && n < 400) return 'Redirection';
  if (n >= 400 && n < 500) return 'Client error';
  if (n >= 500)            return 'Server error';
  return 'Response';
}

function sortObject(o) {
  if (!o || typeof o !== 'object') return o;
  return Object.keys(o).sort().reduce((acc, k) => { acc[k] = o[k]; return acc; }, {});
}

module.exports = { harToOpenapi };
